---
name: pr-security

on:
  pull_request:

permissions:
  actions: read
  security-events: write
  contents: read

jobs:

  
  dependencies-analysis:
    name: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      
      - name: Run OSV Scanner after PR
        uses: google/osv-scanner-action/osv-scanner-action@v2.0.0
        with:
          scan-args: |-
            --format sarif
            --output after.sarif
            ./
        continue-on-error: true

      
      - name: Checkout baseline commit
        run: |
          git checkout ${{ github.event.pull_request.base.sha }}

      
      - name: Run OSV Scanner before PR
        uses: google/osv-scanner-action/osv-scanner-action@v2.0.0
        with:
          scan-args: |-
            --format sarif
            --output before.sarif
            ./
        continue-on-error: true

     
      - name: Compare OSV Reports
        uses: google/osv-scanner-action/osv-reporter-action@v2.0.0
        with:
          scan-args: |-
            --format sarif
            --output diff.sarif
            --new after.sarif
            --old before.sarif
        continue-on-error: true

      
      - name: Save report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: DependenciesAnalysisDiff
          path: diff.sarif

  
  source-code-analysis:
    name: source-code-analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:1.161.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      
      - name: Run Semgrep differential analysis
        run: |
          semgrep scan \
            --config .semgrep \
            --sarif \
            --output semgrep.sarif \
            --baseline-commit ${{ github.event.pull_request.base.sha }}
        continue-on-error: false

      
      - name: Save Semgrep report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SourceCodeAnalysisDiff
          path: semgrep.sarif
