---
name: security

on:
  workflow_dispatch:

permissions:
  
  actions: read
  
  security-events: write
  
  contents: read

jobs:

  # Job #1 : Dependencies Analysis
  dependencies-analysis:
    name: Dependencies Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@v2.0.0
        with:
          scan-args: |-
            --format sarif
            --output DependenciesAnalysisFull.sarif
            ./
        continue-on-error: true

      - name: Upload OSV report to Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: DependenciesAnalysisFull.sarif
          category: dependencies-analysis

  # Job #2 : Source Code Analysis (SAST)
  source-code-analysis:
    name: Source Code Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:1.161.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep Analysis
        run: semgrep scan --config .semgrep --sarif --output semgrep.sarif
        continue-on-error: true

      - name: Upload Semgrep report to Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: source-code-analysis
